// Load test: run the platform in-process against a Postgres and measure throughput and latency per workload.
//   BAAS_TEST_PG_URL=postgres://postgres@localhost/postgres npx tsx scripts/load.ts [seconds] [concurrency]
import { Pool } from "undici";
import { makePlatform } from "../src/platform-testkit.js";

const ADMIN = process.env.BAAS_TEST_PG_URL;
if (!ADMIN) throw new Error("set BAAS_TEST_PG_URL to a superuser Postgres URL");
const seconds = Number(process.argv[2] ?? 8);
const concurrency = Number(process.argv[3] ?? 32);

const t = await makePlatform(ADMIN, { pgBinDir: undefined });
const { gateway } = await t.platform.listen({ api: 0, gateway: 0, host: "127.0.0.1" });
const owner = await t.org();
const p = await t.project(owner, "load");
await t.api("PATCH", `/v1/projects/${p.ref}`, { token: owner, body: { plan: "pro" } });
await t.sql(owner, p.ref, `
  CREATE TABLE public.items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner uuid DEFAULT auth.uid(), body text);
  ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.items TO anon, authenticated;
  CREATE POLICY read_all ON public.items FOR SELECT USING (true);
  CREATE POLICY write_own ON public.items FOR INSERT TO authenticated WITH CHECK (owner = auth.uid());
  INSERT INTO public.items (body) SELECT 'row ' || g FROM generate_series(1, 2000) g;`);
const user = (await t.gw(p.ref, "POST", "/auth/v1/signup", { key: p.anon, body: { email: "load@example.com", password: "secret123" } })).json;
await t.gw(p.ref, "POST", "/storage/v1/bucket", { key: p.service, body: { id: "b", public: true } });
await t.gw(p.ref, "POST", "/storage/v1/object/b/f.txt", { key: p.service, raw: "x".repeat(2048), headers: { "content-type": "text/plain" } });
await t.api("PUT", `/v1/projects/${p.ref}/functions/echo`, { token: owner, body: { source: "export default () => new Response('ok')", verify_jwt: false } });

const pool = new Pool(`http://127.0.0.1:${gateway}`, { connections: concurrency, pipelining: 1 });
const host = `${p.ref}.localhost`;

type Work = { name: string; fn: (i: number) => Promise<number> };
const req = async (method: string, path: string, headers: Record<string, string>, body?: string) => {
  const r = await pool.request({ method: method as "GET", path, headers: { host, ...headers }, body });
  await r.body.text();
  return r.statusCode;
};
const work: Work[] = [
  { name: "REST select (20 rows)", fn: () => req("GET", "/rest/v1/items?limit=20&order=id", { apikey: p.anon }) },
  { name: "REST select by pk", fn: (i) => req("GET", `/rest/v1/items?id=eq.${1 + (i % 2000)}`, { apikey: p.anon }) },
  { name: "REST insert (RLS check)", fn: (i) => req("POST", "/rest/v1/items", { apikey: p.anon, authorization: `Bearer ${user.access_token}`, "content-type": "application/json" }, JSON.stringify({ body: `n${i}` })) },
  { name: "Auth: password login (scrypt)", fn: () => req("POST", "/auth/v1/token?grant_type=password", { apikey: p.anon, "content-type": "application/json" }, JSON.stringify({ email: "load@example.com", password: "secret123" })) },
  { name: "Storage: public download (2 KB)", fn: () => req("GET", "/storage/v1/object/public/b/f.txt", {}) },
  { name: "Function: cold process per call", fn: () => req("POST", "/functions/v1/echo", {}) },
];

console.log(`\n${seconds}s per workload, ${concurrency} concurrent connections, Postgres and platform on one machine\n`);
console.log("workload".padEnd(34), "req/s".padStart(8), "p50".padStart(7), "p95".padStart(7), "p99".padStart(7), "  errors");
for (const w of work) {
  const lat: number[] = [];
  let errors = 0;
  let i = 0;
  const end = Date.now() + seconds * 1000;
  const conc = w.name.startsWith("Function") ? 4 : concurrency; // functions are deliberately capped at 4 per project
  await Promise.all(Array.from({ length: conc }, async () => {
    while (Date.now() < end) {
      const t0 = performance.now();
      const status = await w.fn(i++).catch(() => 0);
      lat.push(performance.now() - t0);
      if (status >= 500 || status === 0 || (status >= 400 && status !== 429)) errors++;
    }
  }));
  lat.sort((a, b) => a - b);
  const q = (x: number) => lat[Math.min(lat.length - 1, Math.floor(lat.length * x))]!.toFixed(1);
  console.log(w.name.padEnd(34), (lat.length / seconds).toFixed(0).padStart(8), q(0.5).padStart(7), q(0.95).padStart(7), q(0.99).padStart(7), `  ${errors}`);
}
await pool.close();
await t.close();
